// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: register.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_register_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_register_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3020000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3020001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_register_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_register_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_register_2eproto;
class Register;
struct RegisterDefaultTypeInternal;
extern RegisterDefaultTypeInternal _Register_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::Register* Arena::CreateMaybeMessage<::Register>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

enum Register_Option : int {
  Register_Option_SEND_MESSAGE = 0,
  Register_Option_USER_LOGIN = 1,
  Register_Option_CONNECTED_USERS = 2,
  Register_Option_USER_INFORMATION = 3,
  Register_Option_STATUS_CHANGE = 4,
  Register_Option_DIRECT_MESSAGE = 5
};
bool Register_Option_IsValid(int value);
constexpr Register_Option Register_Option_Option_MIN = Register_Option_SEND_MESSAGE;
constexpr Register_Option Register_Option_Option_MAX = Register_Option_DIRECT_MESSAGE;
constexpr int Register_Option_Option_ARRAYSIZE = Register_Option_Option_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Register_Option_descriptor();
template<typename T>
inline const std::string& Register_Option_Name(T enum_t_value) {
  static_assert(::std::is_same<T, Register_Option>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function Register_Option_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    Register_Option_descriptor(), enum_t_value);
}
inline bool Register_Option_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, Register_Option* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<Register_Option>(
    Register_Option_descriptor(), name, value);
}
// ===================================================================

class Register final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Register) */ {
 public:
  inline Register() : Register(nullptr) {}
  ~Register() override;
  explicit PROTOBUF_CONSTEXPR Register(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Register(const Register& from);
  Register(Register&& from) noexcept
    : Register() {
    *this = ::std::move(from);
  }

  inline Register& operator=(const Register& from) {
    CopyFrom(from);
    return *this;
  }
  inline Register& operator=(Register&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Register& default_instance() {
    return *internal_default_instance();
  }
  static inline const Register* internal_default_instance() {
    return reinterpret_cast<const Register*>(
               &_Register_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Register& a, Register& b) {
    a.Swap(&b);
  }
  inline void Swap(Register* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Register* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Register* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Register>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Register& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const Register& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Register* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Register";
  }
  protected:
  explicit Register(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef Register_Option Option;
  static constexpr Option SEND_MESSAGE =
    Register_Option_SEND_MESSAGE;
  static constexpr Option USER_LOGIN =
    Register_Option_USER_LOGIN;
  static constexpr Option CONNECTED_USERS =
    Register_Option_CONNECTED_USERS;
  static constexpr Option USER_INFORMATION =
    Register_Option_USER_INFORMATION;
  static constexpr Option STATUS_CHANGE =
    Register_Option_STATUS_CHANGE;
  static constexpr Option DIRECT_MESSAGE =
    Register_Option_DIRECT_MESSAGE;
  static inline bool Option_IsValid(int value) {
    return Register_Option_IsValid(value);
  }
  static constexpr Option Option_MIN =
    Register_Option_Option_MIN;
  static constexpr Option Option_MAX =
    Register_Option_Option_MAX;
  static constexpr int Option_ARRAYSIZE =
    Register_Option_Option_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  Option_descriptor() {
    return Register_Option_descriptor();
  }
  template<typename T>
  static inline const std::string& Option_Name(T enum_t_value) {
    static_assert(::std::is_same<T, Option>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function Option_Name.");
    return Register_Option_Name(enum_t_value);
  }
  static inline bool Option_Parse(::PROTOBUF_NAMESPACE_ID::ConstStringParam name,
      Option* value) {
    return Register_Option_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kSenderFieldNumber = 1,
    kIpFieldNumber = 2,
    kMessageFieldNumber = 3,
    kExtraFieldNumber = 5,
    kFlagFieldNumber = 4,
    kCodeFieldNumber = 6,
  };
  // optional string sender = 1;
  bool has_sender() const;
  private:
  bool _internal_has_sender() const;
  public:
  void clear_sender();
  const std::string& sender() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_sender(ArgT0&& arg0, ArgT... args);
  std::string* mutable_sender();
  PROTOBUF_NODISCARD std::string* release_sender();
  void set_allocated_sender(std::string* sender);
  private:
  const std::string& _internal_sender() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_sender(const std::string& value);
  std::string* _internal_mutable_sender();
  public:

  // optional string ip = 2;
  bool has_ip() const;
  private:
  bool _internal_has_ip() const;
  public:
  void clear_ip();
  const std::string& ip() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_ip(ArgT0&& arg0, ArgT... args);
  std::string* mutable_ip();
  PROTOBUF_NODISCARD std::string* release_ip();
  void set_allocated_ip(std::string* ip);
  private:
  const std::string& _internal_ip() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_ip(const std::string& value);
  std::string* _internal_mutable_ip();
  public:

  // optional string message = 3;
  bool has_message() const;
  private:
  bool _internal_has_message() const;
  public:
  void clear_message();
  const std::string& message() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_message(ArgT0&& arg0, ArgT... args);
  std::string* mutable_message();
  PROTOBUF_NODISCARD std::string* release_message();
  void set_allocated_message(std::string* message);
  private:
  const std::string& _internal_message() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_message(const std::string& value);
  std::string* _internal_mutable_message();
  public:

  // optional string extra = 5;
  bool has_extra() const;
  private:
  bool _internal_has_extra() const;
  public:
  void clear_extra();
  const std::string& extra() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_extra(ArgT0&& arg0, ArgT... args);
  std::string* mutable_extra();
  PROTOBUF_NODISCARD std::string* release_extra();
  void set_allocated_extra(std::string* extra);
  private:
  const std::string& _internal_extra() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_extra(const std::string& value);
  std::string* _internal_mutable_extra();
  public:

  // optional .Register.Option flag = 4;
  bool has_flag() const;
  private:
  bool _internal_has_flag() const;
  public:
  void clear_flag();
  ::Register_Option flag() const;
  void set_flag(::Register_Option value);
  private:
  ::Register_Option _internal_flag() const;
  void _internal_set_flag(::Register_Option value);
  public:

  // optional int32 code = 6;
  bool has_code() const;
  private:
  bool _internal_has_code() const;
  public:
  void clear_code();
  int32_t code() const;
  void set_code(int32_t value);
  private:
  int32_t _internal_code() const;
  void _internal_set_code(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:Register)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr sender_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr ip_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr message_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr extra_;
  int flag_;
  int32_t code_;
  friend struct ::TableStruct_register_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Register

// optional string sender = 1;
inline bool Register::_internal_has_sender() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool Register::has_sender() const {
  return _internal_has_sender();
}
inline void Register::clear_sender() {
  sender_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& Register::sender() const {
  // @@protoc_insertion_point(field_get:Register.sender)
  return _internal_sender();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Register::set_sender(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000001u;
 sender_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Register.sender)
}
inline std::string* Register::mutable_sender() {
  std::string* _s = _internal_mutable_sender();
  // @@protoc_insertion_point(field_mutable:Register.sender)
  return _s;
}
inline const std::string& Register::_internal_sender() const {
  return sender_.Get();
}
inline void Register::_internal_set_sender(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  sender_.Set(value, GetArenaForAllocation());
}
inline std::string* Register::_internal_mutable_sender() {
  _has_bits_[0] |= 0x00000001u;
  return sender_.Mutable(GetArenaForAllocation());
}
inline std::string* Register::release_sender() {
  // @@protoc_insertion_point(field_release:Register.sender)
  if (!_internal_has_sender()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  auto* p = sender_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (sender_.IsDefault()) {
    sender_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void Register::set_allocated_sender(std::string* sender) {
  if (sender != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  sender_.SetAllocated(sender, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (sender_.IsDefault()) {
    sender_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Register.sender)
}

// optional string ip = 2;
inline bool Register::_internal_has_ip() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool Register::has_ip() const {
  return _internal_has_ip();
}
inline void Register::clear_ip() {
  ip_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000002u;
}
inline const std::string& Register::ip() const {
  // @@protoc_insertion_point(field_get:Register.ip)
  return _internal_ip();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Register::set_ip(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000002u;
 ip_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Register.ip)
}
inline std::string* Register::mutable_ip() {
  std::string* _s = _internal_mutable_ip();
  // @@protoc_insertion_point(field_mutable:Register.ip)
  return _s;
}
inline const std::string& Register::_internal_ip() const {
  return ip_.Get();
}
inline void Register::_internal_set_ip(const std::string& value) {
  _has_bits_[0] |= 0x00000002u;
  ip_.Set(value, GetArenaForAllocation());
}
inline std::string* Register::_internal_mutable_ip() {
  _has_bits_[0] |= 0x00000002u;
  return ip_.Mutable(GetArenaForAllocation());
}
inline std::string* Register::release_ip() {
  // @@protoc_insertion_point(field_release:Register.ip)
  if (!_internal_has_ip()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000002u;
  auto* p = ip_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (ip_.IsDefault()) {
    ip_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void Register::set_allocated_ip(std::string* ip) {
  if (ip != nullptr) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  ip_.SetAllocated(ip, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (ip_.IsDefault()) {
    ip_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Register.ip)
}

// optional string message = 3;
inline bool Register::_internal_has_message() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool Register::has_message() const {
  return _internal_has_message();
}
inline void Register::clear_message() {
  message_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000004u;
}
inline const std::string& Register::message() const {
  // @@protoc_insertion_point(field_get:Register.message)
  return _internal_message();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Register::set_message(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000004u;
 message_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Register.message)
}
inline std::string* Register::mutable_message() {
  std::string* _s = _internal_mutable_message();
  // @@protoc_insertion_point(field_mutable:Register.message)
  return _s;
}
inline const std::string& Register::_internal_message() const {
  return message_.Get();
}
inline void Register::_internal_set_message(const std::string& value) {
  _has_bits_[0] |= 0x00000004u;
  message_.Set(value, GetArenaForAllocation());
}
inline std::string* Register::_internal_mutable_message() {
  _has_bits_[0] |= 0x00000004u;
  return message_.Mutable(GetArenaForAllocation());
}
inline std::string* Register::release_message() {
  // @@protoc_insertion_point(field_release:Register.message)
  if (!_internal_has_message()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000004u;
  auto* p = message_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (message_.IsDefault()) {
    message_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void Register::set_allocated_message(std::string* message) {
  if (message != nullptr) {
    _has_bits_[0] |= 0x00000004u;
  } else {
    _has_bits_[0] &= ~0x00000004u;
  }
  message_.SetAllocated(message, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (message_.IsDefault()) {
    message_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Register.message)
}

// optional .Register.Option flag = 4;
inline bool Register::_internal_has_flag() const {
  bool value = (_has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline bool Register::has_flag() const {
  return _internal_has_flag();
}
inline void Register::clear_flag() {
  flag_ = 0;
  _has_bits_[0] &= ~0x00000010u;
}
inline ::Register_Option Register::_internal_flag() const {
  return static_cast< ::Register_Option >(flag_);
}
inline ::Register_Option Register::flag() const {
  // @@protoc_insertion_point(field_get:Register.flag)
  return _internal_flag();
}
inline void Register::_internal_set_flag(::Register_Option value) {
  assert(::Register_Option_IsValid(value));
  _has_bits_[0] |= 0x00000010u;
  flag_ = value;
}
inline void Register::set_flag(::Register_Option value) {
  _internal_set_flag(value);
  // @@protoc_insertion_point(field_set:Register.flag)
}

// optional string extra = 5;
inline bool Register::_internal_has_extra() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool Register::has_extra() const {
  return _internal_has_extra();
}
inline void Register::clear_extra() {
  extra_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000008u;
}
inline const std::string& Register::extra() const {
  // @@protoc_insertion_point(field_get:Register.extra)
  return _internal_extra();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Register::set_extra(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000008u;
 extra_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Register.extra)
}
inline std::string* Register::mutable_extra() {
  std::string* _s = _internal_mutable_extra();
  // @@protoc_insertion_point(field_mutable:Register.extra)
  return _s;
}
inline const std::string& Register::_internal_extra() const {
  return extra_.Get();
}
inline void Register::_internal_set_extra(const std::string& value) {
  _has_bits_[0] |= 0x00000008u;
  extra_.Set(value, GetArenaForAllocation());
}
inline std::string* Register::_internal_mutable_extra() {
  _has_bits_[0] |= 0x00000008u;
  return extra_.Mutable(GetArenaForAllocation());
}
inline std::string* Register::release_extra() {
  // @@protoc_insertion_point(field_release:Register.extra)
  if (!_internal_has_extra()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000008u;
  auto* p = extra_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (extra_.IsDefault()) {
    extra_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void Register::set_allocated_extra(std::string* extra) {
  if (extra != nullptr) {
    _has_bits_[0] |= 0x00000008u;
  } else {
    _has_bits_[0] &= ~0x00000008u;
  }
  extra_.SetAllocated(extra, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (extra_.IsDefault()) {
    extra_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Register.extra)
}

// optional int32 code = 6;
inline bool Register::_internal_has_code() const {
  bool value = (_has_bits_[0] & 0x00000020u) != 0;
  return value;
}
inline bool Register::has_code() const {
  return _internal_has_code();
}
inline void Register::clear_code() {
  code_ = 0;
  _has_bits_[0] &= ~0x00000020u;
}
inline int32_t Register::_internal_code() const {
  return code_;
}
inline int32_t Register::code() const {
  // @@protoc_insertion_point(field_get:Register.code)
  return _internal_code();
}
inline void Register::_internal_set_code(int32_t value) {
  _has_bits_[0] |= 0x00000020u;
  code_ = value;
}
inline void Register::set_code(int32_t value) {
  _internal_set_code(value);
  // @@protoc_insertion_point(field_set:Register.code)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::Register_Option> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Register_Option>() {
  return ::Register_Option_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_register_2eproto
